name: CI
on:
  pull_request:
    branches:
      - development
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run build
      - run: npm run test
